### ISSUE TITLE
Unimplemented arc_center, arc_start, and arc_end

### ISSUE THREAD

**Issue by AaronBallman** [ISOCPP-2D/P0267_RefImpl#3]
xgraphicsmath.h has declarations for arc_start(), arc_end(), and arc_center() that accept a point, an angle, and another point, but these declarations do not have definitions. Only the functions accepting a fourth argument of a matrix are implemented.

**Comment by mikekazakov** [comment]
Fixed according to the paper in 9ae456048f5771efda9a43eefca867eff75592c0.
Still in a the "new_structure" branch.
